#!/bin/bash

# script/deploy: Push the books to the gh-pages branch

set -e

cd "$(dirname "$0")/.."

# Set email and username
git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
git config --global user.name "$GH_NAME" > /dev/null 2>&1

rm -rf vendor

# Switch to gh-pages branch and pull from origin
git checkout gh-pages --force
git pull --rebase origin gh-pages

# Clean up
# git clean -fx _book
git clean -fx .bundle
git clean -fx node_modules
git clean -fx vendor
git clean -fx .ruby-version

mv _book/* .

git add .
git commit -m "update book [ci skip]"

echo -e "\n\n"
echo "==> Deploying..."
echo -e "\n\n"

git push
